spring:
  application:
    name: guarantees-module-cqrs
  
  # Command Database (Write Side) - Normalized
  datasource:
    url: ${COMMAND_DB_URL:jdbc:mysql://localhost:3306/guarantees_command_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${COMMAND_DB_USERNAME:guarantees_command_user}
    password: ${COMMAND_DB_PASSWORD:guarantees_command_pass}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
    # Query Database (Read Side) - Denormalized
    query:
      url: ${QUERY_DB_URL:jdbc:mysql://localhost:3306/guarantees_query_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${QUERY_DB_USERNAME:guarantees_query_user}
      password: ${QUERY_DB_PASSWORD:guarantees_query_pass}
      hikari:
        maximum-pool-size: 50
        minimum-idle: 10
        idle-timeout: 300000
        connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: guarantees-cqrs-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 10
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        spring.json.trusted.packages: "com.interexport.guarantees.*,java.util.*"
    producer:
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 1000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        batch.size: 16384
        linger.ms: 50
        buffer.memory: 33554432

# CQRS Configuration
cqrs:
  command:
    database: command
  query:
    database: query
  events:
    topics:
      guarantee-created: guarantee-created
      guarantee-updated: guarantee-updated
      guarantee-approved: guarantee-approved
      claim-submitted: claim-submitted
      amendment-created: amendment-created
    partitions: 3
    replication-factor: 1
